### ISSUE TITLE
Fix FIND ME HERE Section

### ISSUE THREAD

**Issue by virendracarpenter** [virendracarpenter/virendracarpenter#1]
Need to Fix FIND ME HERE section elements aligments. 
Fix space between Them.

**Comment by kaustav202** [comment]
lat me fix this @virendracarpenter

**Comment by sujal-goswami** [comment]
Hello, virendracarpenter I want to work on this issue can you please assign this issue to me.

**Comment by sujal-goswami** [comment]
or can you also put hacktoberfest label on this issue as I am a beginner this issue is great for Me to participate in hacktoberfest.

**Comment by virendracarpenter** [comment]
@sujal-goswami sure, happy coding

**Comment by virendracarpenter** [comment]
@kaustav202 okay, all the best

**Comment by sujal-goswami** [comment]
> or can you also put hacktoberfest label on this issue as I am a beginner this issue is great for Me to participate in hacktoberfest.

?
